### ISSUE TITLE
Unable to delete Inner HTML value

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Launcher#108]
After I add some Inner HTML value I can't remove it.
To remove the value I have to add a space and save it like this.

**Comment by tomalec** [comment]
From what I have tested you do not have to add space, just clicking or pressing any key on this fild should also work. 
So the reason seems to be the fact that onclick handler is not called when delete or backspace is pressed on selection.

**Comment by miyconst** [comment]
Yes, "click" into the field somehow works for me.
