### ISSUE TITLE
Workspaces should not be case sensitive

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Launcher#110]
As discussed today on Skype between me and @miyconst, the middleware delegate function in https://github.com/Polyjuice/Polyjuice/blob/master/src/LauncherHelper.cs searches for existing workspace in case sensitive manner:

```
                if (appName == launcher.workspaces[i].appName) {
                    foundWorkspace = (Launcher.workspacesElementJson)launcher.workspaces[i];
                    break;
                }
```

So if application morphs from page: `/signIn/somepage` to `/signin/otherpage`, the response creates a new workspace instead of using the existing page.

The check should be case insensitive.

Please add a test to it in https://github.com/Polyjuice/Launcher/tree/master/test

**Comment by miyconst** [comment]
@warpech I have created the test, but it requires Launcher & SignIn apps running together.
Is there any way I could use appName without any real app running?

**Comment by warpech** [comment]
`appName` (and workspaces) is a feature of Launcher, so it can only be tested with Launcher and some app.

**Comment by warpech** [comment]
@parherman could you make SignIn app start with the test so it can pass?

**Comment by parherman** [comment]
Added! It builds before launcher

**Comment by miyconst** [comment]
@warpech, @parherman the test won't work with the master branch of SignIn app.
 I will uncomment the test when the cookie-rework branch merged with master.

**Comment by miyconst** [comment]
The test has been uncommented and successfully passed.
