### ISSUE TITLE
Error 404: File /launcher/launchertemplate.html. not found

### ISSUE THREAD

**Issue by parherman** [Polyjuice/Launcher#112]
When I build with:

> C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe Launcher.sln /p:ReferencePath="C:\Program Files\Starcounter\2.0.3125.3;C:\Program Files\Starcounter\2.0.3125.3/EditionLibraries" /p:Configuration=Release /maxcpucount /verbosity:minimal

And then do:
> star --database=PolyjuiceTestsDb "bin/Release/Launcher.exe"

I get:
> Error 404: File /launcher/launchertemplate.html. not found

When I go to http://localhost:8080/

**Comment by warpech** [comment]
Maybe that is because "bin" is not a sibling directory of "wwwroot" anymore?

cc @alemoi

**Comment by alemoi** [comment]
Haha, that's correct! Do you remember when we talked that wwwroot should be a sibling of bin, we simply forgot about it. Let's talk tomorrow how it should be.

**Comment by alemoi** [comment]
As a workaround now, I can add one more lookup path for wwwroot during bootstrap.

**Comment by warpech** [comment]
I think it's fine... Will you deduct the path to `..\..\src\<project name>\wwwroot` from the executable filename?

**Comment by miyconst** [comment]
@alemoi, can this issue be closed?

**Comment by alemoi** [comment]
Yes, closing this one. Thanks for noticing!
