### ISSUE TITLE
Layout editor: collapse all groups by default

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Launcher#115]
All editor groups should be collapsed by default.

**Comment by miyconst** [comment]
The sidebar has been reworked a lot recently, I don't see the need to collapse all of the groups any more.

**Comment by warpech** [comment]
I think it is still a good idea. The same way as tree in File Explorer works: all folders are collapsed by default, until you expand them or select something inside them:

![Windows Explorer](http://designinginterfaces.com/firstedition/Patterns/Two-Panel_Selector/windows-explorer.gif)

**Comment by miyconst** [comment]
I can't disagree, just it is not very important for me, as it was before.
