### ISSUE TITLE
Layout editor: add hot keys

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Launcher#117]
Short cut keys might be useful.

- [ ] `Shift + G` - group selected elements
- [ ] `Shift + U` - ungroup selected groups
- [ ] `Shift + D` - delete styles for selected elements
- [ ] `Shift + O` - expand all groups
- [ ] `Shift + L` - collapse all groups
- [ ] `Shift + S` - save changes

**Comment by miyconst** [comment]
@warpech do you think any of those keys would be useful?

**Comment by warpech** [comment]
I would prefer to avoid having them, for 3 reasons:
- I know from experience that keyboard shortcuts in web apps are difficult to maintain and test
- You are renaming a tree element. You have text cursor in the `<input>` field. What should happen after "Shift + S" is pressed? Add uppercase "S" to the input or save the setup?
- There might be another app that also wants to register the same hot key and we become part of a conflict.

Most importantly, there should be no hot key that does not have a corresponding toolbar button.

Maybe "Expand all groups", "Collapse all groups" should then be added as buttons in the top part of the sidebar?

**Comment by miyconst** [comment]
I like the last idea.

**Comment by warpech** [comment]
Let it be then :)

**Comment by miyconst** [comment]
Done. Now there are three buttons in the top right corner of sidebar:
1. Expand all.
2. Collapse all.
3. Show all.
