### ISSUE TITLE
Layout editor: scroll page to selected element

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Launcher#118]
Sidebar tree scrolls itself when an html element selected, but the page should also be scrolled when a tree item selected.

**Comment by warpech** [comment]
It looks like it is already done. Am I wrong?

**Comment by miyconst** [comment]
No, it's not. Lets say we have a very long page with a scroll, then in sidebar scroll down to an element which is not visible on the page and click it to select. The page won't scroll down to the element.

It works in other direction. If scroll down the page and select an element which is not visible in sidebar tree, then sidebar tree will scroll itself to the element.

**Comment by warpech** [comment]
Then I don't think the scrolling in question should be implemented. It may turn out to be hard to maintain.

**Comment by miyconst** [comment]
Okay, current layout editor is good enough.
