### ISSUE TITLE
Layout editor: shorten default names

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Launcher#119]
Default group names should be shorten somehow to remove horizontal scroll bar, for example: `/Products/viewmodels/EditProductPage.html` may be `EditProductPage.html`, `/Launcher/workspaces/products` may be `products`.

**Comment by tomalec** [comment]
These are not group names, but Partial Ids, and we cannot shorten them
Right now there is a way to provide custom label for it, which will be used only as a display alias.

**Comment by miyconst** [comment]
Okay, I just wanted to rid off horizontal scroll in the sidebar.

**Comment by warpech** [comment]
I agree with @miyconst that their display value should be shortened. Please proceed with showing `/Products/viewmodels/EditProductPage.html` as `EditProductPage.html`. The full value should be displayed on title tooltip.
