### ISSUE TITLE
Layout editor: add hot key to open/close editor

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Launcher#121]
`Ctrl + ~` works perfect for SDA, something similar should be made for layout editor.

**Comment by warpech** [comment]
I was thinking about the same! `Ctrl + E` (`Cmd + E` for Mac) is a good idea, I think.

`Cmd + L` on Chrome/Mac selected the address bar, which is too useful to replace.

**Comment by warpech** [comment]
`Esc` should hide the editor

**Comment by miyconst** [comment]
`Ctrl + E` is a custom Chrome short-cut. It focuses address bar and fills it with `?` to start search.

Used `Сtrl + Z` short cut. Could be easily changed to any other key.

Created custom `launcher-hot-key` element which accepts keys and fires it's `keyup` event when such keys pressed. Simple example:

```html
<launcher-hot-key keys="Ctrl+Z Esc" onkeyup="getModel(this).editingMode$ = !getModel(this).editingMode$"></launcher-hot-key>
```

**Comment by warpech** [comment]
Do you use the `Ctrl + E` feature of Chrome? I am asking because I don't and never heard of anyone doing that, but know many people including myself who use `Ctrl + Z` for undo...

Does it help that `Ctrl + E` on Windows seems to be also mapped to `Ctrl + K`? On Mac it is available via `⌘-Option-F`.

**Comment by miyconst** [comment]
I use `Ctrl + E` very seldom, and `Ctrl + Z`  was just a temporary solution. Replaced it with `Ctrl + E` as you confirmed that you (and hopefully others) don't use this chrome shortcut.

**Comment by warpech** [comment]
Looks ok!
