### ISSUE TITLE
Layout editor: automatically select root element on open

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Launcher#123]
Layout editor should automatically select root group instead of showing empty sidebar when opened.

**Comment by tomalec** [comment]
By 'root group', do you mean 'the first juicy-tile-list (or -grid) that is in highest position in DOM tree`?
So in fact, this should be the first element of [reducedInductedSpanningTree](https://github.com/Juicy/juicy-tile-editor/blob/gh-pages/src/juicy-tile-editor.js#L14): `juicy-tile-editor.tree[0]`

This is duplicate of https://github.com/Juicy/juicy-tile-editor/issues/37

**Comment by miyconst** [comment]
Yes, by root I mean the highest possible element inside sidebar.

**Comment by warpech** [comment]
Approved, but first let's solve https://github.com/Juicy/juicy-tile-editor/issues/37

**Comment by miyconst** [comment]
The issue is not relevant, I guess. The sidebar tree is automatically rendered on open, and we never apply styles for the very root element, so no need to select it.

**Comment by tomalec** [comment]
Just to note, we did few times change gap of root container, but I agree it's almost never.

**Comment by miyconst** [comment]
Agree, this is useful when need a gap between layouts of two (or more apps). The only way to add this gap is to apply gap for the very top container, but I still don't think we should select the parent container on load.
