### ISSUE TITLE
Layout editor: add button unhide all

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Launcher#124]
Sometimes I hide an element on a page and then could not figure out what should I unhide to see the element again.

A button `unhide all` would be useful.

**Comment by warpech** [comment]
Approved

**Comment by miyconst** [comment]
The button does not work on this page: http://juicy.github.io/juicy-tile-editor/, but works on this: http://juicy.github.io/juicy-tile-editor/examples/juicy-tiles-grid-editor.html
