### ISSUE TITLE
Layout editor: display actual group id instead of user friendly name

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Launcher#125]
I would prefer to see actual group/element ids in the sidebar instead of user friendly name. This would make raw json editing more simple.

The ids may be automatically set to user friendly name though.

**Comment by tomalec** [comment]
:+1:
I have added tile id's into tree view as item title, but it would be nice to have it also somewhere else, and more visible.

**Comment by miyconst** [comment]
I guess you missed an item there, fixed it.

**Comment by warpech** [comment]
Maybe add a switch at the bottom of the sidebar to choose showing the id or the friendly name?

**Comment by miyconst** [comment]
Don't know. After all of those improvements, it feels like this feature is not needed any more.

I would like to see this one done: https://github.com/Polyjuice/Polyjuice/issues/37

**Comment by warpech** [comment]
You are the person who worked the most with layout editing recently, so I trust your judgement. @tomalec do you agree titles are fine for now? Then let's close the issue

**Comment by tomalec** [comment]
I would only add id somewhere in top menu, even in small brackets under the name field or so, to be able to copy it and search in raw JSON. but it is not very important

**Comment by miyconst** [comment]
I replace `Container` title in the top panel with item's id, if only one item selected. Looks like this: 
![juicy-tile-editor-id](https://cloud.githubusercontent.com/assets/6435556/7541551/f5d8f0fa-f5be-11e4-92a8-dc3844b08d21.png), the yellow color is just to mark the changed element.

Closing the issue for now.
