### ISSUE TITLE
Cannot find function or filter: forceJson

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Launcher#126]
Steps to reproduce:

1. Start Launcher and any other app.
2. Open a page of an app.
3. Open layout editor and modify any element.
4. Select any element inside `launchpadGrid` sidebar menu.
5. Press `Save` button. There will be an exception on console:

```
Cannot find function or filter: forceJson
Filter.transform @ polymer.js:3409
Expression.setValue @ polymer.js:3674
setValueFn @ polymer.js:3654
ObserverTransform.setValue @ polymer.js:5367
properties.createPropertyAccessor.Object.defineProperty.set @ polymer.js:10939
Polymer.save @ juicy-tiles-setup-sync.html:70Polymer.saveChanges @ juicy-tile-editor-form.js:263
events.dispatchMethod @ polymer.js:9131
events.getEventHandler @ polymer.js:10715
```

**Comment by miyconst** [comment]
@warpech should `launchpadGrid` items be editable?

**Comment by warpech** [comment]
> @warpech should launchpadGrid items be editable?

I don't think so

The `forceJson` filter is defined in https://github.com/Polyjuice/Launcher/blob/master/src/Launcher/wwwroot/Launcher/elements/launcher-launchpad/launcher-launchpad.html#L53

Maybe the workaround can already be removed? @tomalec?

**Comment by tomalec** [comment]
I'm afraid it cannot as https://github.com/Starcounter/Starcounter/issues/2571 is still opened, so probably we cannot send Patches to setup. `forceJSON` is to convert string returned by SC to JSON

**Comment by miyconst** [comment]
I don't see this exception any more, and it looks like @chrhol has fixed https://github.com/Starcounter/Starcounter/issues/2571, @tomalec can you confirm that it is fixed?

**Comment by tomalec** [comment]
I'm not sure if forceJson issue is fixed, as currently there is no setup for launchpad coming.

**Comment by tomalec** [comment]
Ok, I'll goo with clean solution, so forceJson will not be needed
