### ISSUE TITLE
Search does not hide workspaces

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Launcher#128]
Today I discovered some problems with search:

- when searching in Launcher from Launchpad, the Launchpad does not hide 
- when searching in Launcher from People app, the workspace of the People app does not hide

Starcounter 2.0.3146.3, all apps from master

@miyconst could you investigate? ask @tomalec when not sure about how workspaces work

**Comment by tomalec** [comment]
It seems that changing search query does not update URL => `warpech-display-router` is not notified to switch workspaces.

**Comment by warpech** [comment]
How did it work before?

**Comment by tomalec** [comment]
Search handler updated `searchEngineResultPageUrl` https://github.com/Polyjuice/Launcher/blob/master/src/Launcher/viewmodels/Launcher.json.cs#L27 which is propagated to `juicy-redirect` https://github.com/Polyjuice/Launcher/blob/master/src/Launcher/wwwroot/Launcher/LauncherTemplate.html#L52

**Comment by warpech** [comment]
@miyconst can you try to fix that based on the above info?

**Comment by miyconst** [comment]
@warpech sure, will do that.

**Comment by miyconst** [comment]
There is some issue with patches. The client does not receive patch to update `searchEngineResultPageUrl$` value.

Here https://github.com/Polyjuice/Launcher/blob/master/src/Launcher/viewmodels/Launcher.json.cs#L24 `resp.searchEngineResultPageUrl` is empty.

But even if I add: 
```csharp
launcher.searchBar.searchEngineResultPageUrl = "/launcher/search?query=" + HttpUtility.UrlEncode(query);
```

After https://github.com/Polyjuice/Launcher/blob/master/src/Launcher/api/LauncherHelper.cs#L114 the client still does not receive the update.

Patches from `resp`:
```json
{  
    "_ver#c$":1,
    "_ver#s":0,
    "Html":"/Launcher/LauncherTemplate.html",
    "homeThumbnail":{},
    "homeUrl":"",
    "editingMode$":false,
    "searchBar":{  
        "query$":"1",
        "searchEngineResultPageUrl$":"/launcher/search?query=1",
        "feedback":[]
    },
    "results":{  
        "Launcher":{  
            "Html":""
        },
        "Html":""
    },
    "user":{  
        "Launcher":{  
            "Html":""
        },
        "Html":""
    },
    "menu":{  
        "Launcher":{  
            "Html":"/Launcher/LauncherMenu.html"
        },
        "Html":"/polyjuice/htmlmerger?Launcher=/Launcher/LauncherMenu.html",
        "AppName":"Launcher",
        "PartialId":"/Launcher/LauncherMenu.html"
    },
    "launchpad":{  
        "icons":{  
            "Launcher":{  
                "Html":""
            },
            "Html":""
        },
        "names":{  
            "Launcher":{  
                "Html":""
            },
            "Html":""
        }
    },
    "dashboard":{},
    "appFilter":[],
    "uri":"",
    "workspaces":[]
}
```

And the patch which client receives:
```json
[  
    {  
        "op":"replace",
        "path":"/_ver#s",
        "value":1
    },
    {  
        "op":"test",
        "path":"/_ver#c$",
        "value":1
    },
    {  
        "op":"replace",
        "path":"/results",
        "value":{  
            "Launcher":{  
                "Html":""
            },
            "Html":""
        }
    }
]
```

The search query for this test was `1`, no other apps except launcher were running.

@alemoi, @chrhol could you please take a look?

**Comment by chrhol** [comment]
@miyconst: I think something with setting the parent (https://github.com/Polyjuice/Launcher/blob/master/src/Launcher/viewmodels/Launcher.json.cs#L28-L30) messes something up. If I remove these lines the `searchEngineResultPageUrl` gets sent to the client correctly.

Do you know why the parent is set each time?

**Comment by miyconst** [comment]
@chrhol, sorry, but I have no idea.

The code was not written by me.

I tried to replace it with:

```csharp
if (resp != null && this.Parent == null) {
	this.Parent = resp;
}
```

The search seems to work, but when I click on a search result link I got a js error:
```
apply @ json-patch-duplex.js:601
Puppet.validateAndApplySequence @ puppet.js:561
applyOT @ json-patch-ot-agent.js:71
JSONPatchQueue.receive @ json-patch-queue.js:66
Puppet.handleRemoteChange @ puppet.js:595
(anonymous function) @ puppet.js:212
PuppetNetworkChannel.xhr.req.onload @ puppet.js:268
```

at 

```javascript
obj = obj[key];
```

The last json patch which causes the exception is available here:
https://jsfiddle.net/n5u9hze3/

**Comment by alemoi** [comment]
> Do you know why the parent is set each time?

Yeah, this code seems very strange and should be avoidable as we talked to even maybe restrict access to Parent.

**Comment by tomalec** [comment]
I think, it's a legacy from early days of the Launcher. So, probably it's
not needed any longer.
5 maj 2015 01:02 "Alexey" <notifications@github.com> napisał(a):

**Comment by miyconst** [comment]
Removed the `this.Parent = resp;` at all https://github.com/Polyjuice/Launcher/commit/a581ddbfd2a3217c19d8f84b17672b34175d73c9

The search works, but the js exception still here. Steps to reproduce:

1. Start Launcher.
2. Start People.
3. In search field input some text and find a person or an organization.
4. Click any person or organization link in the search result.
5. There will be blank workspace and js error on console.

**Comment by chrhol** [comment]
I will take a look

**Comment by chrhol** [comment]
I have reproduced it. It looks like there is an extra patch that comes before the workspace is added. Probably something I did in the current "fix" :)

**Comment by chrhol** [comment]
This problem was not from the latest fix I did. Rather it is happening because we use the same json (Master from People) both as result from search and as workspace for People when an orgnaization or person is clicked, which means we have the same json in two different places in the viewmodel.

When the CurrentPage is updated an incorrect patch is generated. the path for the first patch below should be `/results/People/CurrentPage`, but the wrong sibling are used when determining the path. I'm not quite sure yet how to solve this properly.

```javascript
[ 
    ...
    {
        "op": "replace",
        "path": "/workspaces/0/People/CurrentPage",
        "value": ...
    },
    {
        "op": "add",
        "path": "/workspaces/0",
        "value": ...
    }
]
```

This should of course work (and is needed to work) but until then a fix for the People-app is to not return Master, but Master.CurrentPage (from https://github.com/Polyjuice/Polyjuice/issues/56) in all places.

**Comment by miyconst** [comment]
@warpech is the search that important to fix People and other apps with the temporary fix?

**Comment by miyconst** [comment]
Search works fine now, can this issue be closed?

**Comment by warpech** [comment]
Yes, thanks for checking!
