### ISSUE TITLE
Launcher icons appear on top of the layout editor

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Launcher#130]
The "Home" and "Search" icon incorrectly renders on top of the layout editor sidebar:

![screenshot 2015-05-12 09 56 27](https://cloud.githubusercontent.com/assets/566463/7582384/491ec89a-f88d-11e4-82ac-97e00cdcaab0.png)

**Comment by miyconst** [comment]
Can't reproduce the bug under Chrome/windows, probably need to see your screen to fix this.

**Comment by warpech** [comment]
Reproducible on Windows as well. Running only Launcher on Starcounter 2.0.3164.3, with sidebar attached to the left edge of the screen.

![windows](https://cloud.githubusercontent.com/assets/566463/7588176/b25fb3fe-f8bb-11e4-89c2-994a0d386952.png)

Call me if you need more details

**Comment by miyconst** [comment]
Okay, I got the exception, it appears if the sidebar was attached to the left side on page load, but not if I drag it from right side.
