### ISSUE TITLE
Extend <include-template> with Launcher specific layout management features

### ISSUE THREAD

**Issue by tomalec** [Polyjuice/Launcher#132]
Idea is to have juicy-tile-grid, [layout features](https://github.com/Polyjuice/Launcher/wiki/Layout-setup), and all Polyjuice magic put for every (https://github.com/Polyjuice/Launcher/issues/40) `<imported-template>` used by app dev 

Draft of spec in wiki https://github.com/Polyjuice/Launcher/wiki/include-template-in-Polyjuice

Umbrella in here: https://github.com/Polyjuice/Launcher/issues/114

**Comment by tomalec** [comment]
Besides the problems marked at wiki, I would said that the biggest obstacles are:

# Siblings vs nesting
`<template is="imported-template">` (or future `include-template`) puts output on sibling level, but in Polyjuice we pack it into the tiles-grid, so even if we would hide it into ShadowDOM, it is still a container that separates it from sibling.

I recall that this sibling feature was quite important, not only as it correcponds to polymer's template binding, and reducts div soup, but it gives the developer an opportunity to use hers/his own structure.

On the other hand we need a separated set of tiles to arrange.

Leaving it as it is will cause lots of bugs  and confusion (as we already experienced), as the same app launched in launcher simply crashes
 
As we cannot givup with tiles, the only solution I can see is to create new Juicy/`<imported-partial>` which will be in fact `<imported-template>` wrapped within a div, but it's 
 - more likely to become native/standard/unopinionated
 - seems to me kind of useless when standalone
 - may still lead to confusion, as app dev may use both


# Forced no-layout
My doubt from the very beginning was the fact, that app developer, who is aware of polyjuice features, may like to use imported template, or even partial features without layout. @warpech also started to share similar doubt in regards of Tunity migration, from what I have seen @miyconst already use this in code. I would divide this problem into:

 1. App dev wants to insert Polyjuice(merged) partial, but without juicy tiles, and layout stuff (to use it in her/his own cool canvas angrybirds layout manager, or whatever)
 2. wants only her/his App partial, without other apps mess, and w/o layout magic
 3. wants only his/her App partial, with layout features

For 1. @waprech proposed `no-layout` attribute in HTML Partial insertion point (`include-template` custom element). It will look weird in standalone app with 'native'(Juicy) `imported-template`, but experienced Polyjuice dev will know that it's important, plus layout will be enabled by default on 'native' imported-templates

Again, I'm afraid we have somehow contradictory expectations, as we would like to be unopinionated and make layout implicit for partials, force UI mixing on Partial level and let app dev to disable layouts and mixing.

@Starcounter-Jack , @warpech , @miyconst any ideas/comments on this or wiki?

**Comment by warpech** [comment]
I think he have to live with the fact that `<include-template>` wraps templates in an element. Inside it can use `<template is="imported-template">` in an unchanged form. 

This will make it easier for us to get ready for Polymer 1.0. I don't think there are any real problems win wrapping templates in an element, since this is what `<launcher-root-partial>` already does.

**Comment by miyconst** [comment]
I agree with @warpech, currenty I have to manualy wrap `<template is="imported-template">` in a div to make layout editor work as it should.

**Comment by tomalec** [comment]
There are no problems in wrapping `imported-template` into dive when it's used as a tile, as this is by tile definition - it should be single element. @miyconst you "have to.." wrap it to "make **editor** work", not to make template work.
`imported-template` works as it should when not wrapped, and there are cases where we use it in purpose as a sibling.

**Comment by warpech** [comment]
Conclusion from today's meeting with @tomalec and @miyconst:

A new `<polyjuice-include>` element should be included in Starcounter /sys/ directory, which is actually `<template is="imported-template>` wrapped in a custom element.

Launcher (or Layout app in future) overwrites the definition of  `<polyjuice-include>` to add the capabilies of `<juicy-tile-list>` to it. Technically it means to rename `<launcher-root-partial>` to `<polyjuice-include>` in launcher **and all the apps**.

**Comment by tomalec** [comment]
To explain it a little, that means, that when app developer wands to make a partial in Polyjuice (that gets Polyjuice mixing, and layout features)  he needs to specifically:
 - use `Self.GET` for insertion point in server-side
 - use `<polyjuice-include>` for insertion point in HTML

In Polyjuice documentation, we will explain that from HTML perspective developers should expect `<div><template is="include-template"></template></div>` behavior from `<polyjuice-partial>`, and that each Launcher may add its own sugar on top of it.

(so we are going back to previous wiki description, with new names ;) )

**Comment by warpech** [comment]
Is this done?

**Comment by tomalec** [comment]
I think so. As we agreed [`launcher-include`](https://github.com/Polyjuice/Launcher-include) is extended/hijacked version of [`<polyjuice-include>`](https://github.com/Polyjuice/polyjuice-include).

How it works is described at [wiki](https://github.com/Polyjuice/Launcher/wiki/include-template-in-Polyjuice)
