### ISSUE TITLE
Different cog color for unsaved changes in layout editor

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Launcher#133]
As discussed in https://github.com/Polyjuice/Polyjuice/issues/53, there should be an alternative color for the cog (or maybe some orange dot on it's corner?) indicating that the layout was not saved before collapsing the editor.

![screenshot 2015-06-02 13 27 15](https://cloud.githubusercontent.com/assets/566463/7934818/408ac536-092b-11e5-9bde-3bff2b0be91b.png)

**Comment by miyconst** [comment]
After https://github.com/Polyjuice/Launcher/issues/134 the cog icon is no longer visible when side bar at the right side.

Should we think up some better way to notify user about unsaved changes?

**Comment by warpech** [comment]
With layout editor opened, user knows that he has unsaved changes because Save / Revert icons are active.

With layout editor closed, user doesn't know if there are any unsaved changes. This is the problem that we are trying to solve (previous attempt was here: https://github.com/Polyjuice/Polyjuice/issues/53)

**Comment by miyconst** [comment]
Okay. Taking the issue.

**Comment by miyconst** [comment]
Done, looks like this:
![launcher-layout-modified](https://cloud.githubusercontent.com/assets/6435556/8029032/a3a5304a-0dc0-11e5-99d2-a8ed3bbdd963.png)
Could not find any better color, which would indicate the "changed" state, but not too bright.

Also added a title to the red cog: "You have unsaved layout changes on this page!".

To achieve this result I exposed `modified` property of `juicy-tile-editor-form` to outside world, and bound the cog's style to the value in the Launcher.

**Comment by warpech** [comment]
Done right, thanks! Visually could be better, but [there aren't too many great patterns to follow](http://ux.stackexchange.com/questions/41038/is-there-a-better-character-than-the-asterisk-to-indicate-a-modified-document).

**Comment by miyconst** [comment]
I like the asterisk symbol for this purpose, but in our case we don't have any place to put it in.
