### ISSUE TITLE
Add a X button to close the layout editor

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Launcher#134]
Currently, the cog icon is used to close the layout editor:

![screenshot 2015-06-02 14 35 22](https://cloud.githubusercontent.com/assets/566463/7935898/d6c356e0-0934-11e5-9436-0f8587e98856.png)

It would be better to use a "X" button to close the layout editor if it's opened:

![screenshot 2015-06-02 14 36 53](https://cloud.githubusercontent.com/assets/566463/7935964/58e74d16-0935-11e5-8ded-5ed87e31fcc8.png)

The above is just a visualization. Probably the icon could be smaller :)

**Comment by miyconst** [comment]
I have added `cancel` icon from `font-awesome` to `jte` collection and used it.

**Comment by warpech** [comment]
My thought was that the "X" icon should be added in Launcher, not in `juicy-tile-editor`. Launcher shows it, so Launcher should hide it.

**Comment by warpech** [comment]
On similar note, is `CTRL+E` hotkey implemented in `juicy-tile-editor` or Launcher?

**Comment by miyconst** [comment]
`launcher-hot-key` is implemented in Launcher.

The **X** button does not close the editor, it fires and event, and the Launcher closes it. The dialog windows have own close button, but not the opener of the dialog provides the close button.

**Comment by warpech** [comment]
Fair enough, thanks!
