### ISSUE TITLE
Add favicon.ico

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Launcher#135]
By default Chrome looks for favicon in the root `/favicon.ico`, this leads to 
`GET http://localhost:8080/favicon.ico 404 (NotFound)` error on console.

We have to add a `<link rel="shortcut icon" href="/path/to/our/icon/favicon.ico" />` or put an icon to the root folder.

**Comment by miyconst** [comment]
I was brave enough to add `favicon.ico` from starcounter.io without approval :-)

**Comment by warpech** [comment]
Better than nothing :)
