### ISSUE TITLE
Search has a very annoying behaviour

### ISSUE THREAD

**Issue by malx122** [Polyjuice/Launcher#136]
Searching in the searchbar gives ridiculous web browser history. Searching should not affect webbrowser history (or replace anything on screen) before "enter" has been pressed. Live results could(and should) be shown but via popup or something like that.

Look at google.com, facebook or any other known application on how it should work.

**Comment by warpech** [comment]
I agree.

Another thing is that Facebook/Google have different search result views for the suggestion area and for the SERP area. I think we can achieve that as well using `CallLevel`.

**Comment by miyconst** [comment]
I have added search preview popup and redirect to search url by `enter` key or by `search` icon-button press.

@warpech take a look and close the issue if you like it, please.

**Comment by miyconst** [comment]
Ping @warpech.
