### ISSUE TITLE
Show an error message if CSS Grid is not supported

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Launcher#145]
There should be a fatal error message in Launcher if it is accessed in an unsupported browser. 

This is related but not the same as https://github.com/Juicy/juicy-tile-grid/issues/7, which is about an error in the console.

I propose the following text for the error message:

> This app requires support for CSS Grid Layout in your web browser. 

> To enable it in Google Chrome:
> 1. Go to "chrome://flags"
> 2. Search for "Enable experimental Web Platform features" option
> 3. Press "Enable" link
> 4. Restart Chrome

> We are working on extending support to all modern web browsers.

**Comment by miyconst** [comment]
Should I check whether browser actually supports css grid, or just check the browser to be Chrome + Web Platform features?

This page says that css-grid could be achieved in any browser: http://igalia.github.io/css-grid-layout/enable.html

But this example: http://gridbyexample.com/examples/code/example2.html works in Chrome and Opera only. Firefox displays it in a wrong way, and MSIE does not care about `-ms-grid-x` at all.

The thing is that we also need native WebComponents support, not only css grid.

**Comment by warpech** [comment]
You cannot check if "Web Platform features" flag is enabled and I think this is a good thing. You need to do feature detection for a particular feature that you want to have. 

As proposed by @tomalec in another issue, I think that a simple CSS selector:

```css
@supports( (display: grid) ){
    .feature-detection{
        display: none;
    }
}
```

will rule out all browsers that don't have the proper support for CSS Grid Layout. I guess we should literally not restrict ourselves to Chrome. If Opera, Vivaldi and other Chromium-based browsers support CSS Grid Layout, we should allow them.

Do we really rely on native web components? Then why is the webcomponents.js shim included in Launcher? https://github.com/Polyjuice/Launcher/blob/master/src/Launcher/wwwroot/Launcher/viewmodels/LauncherTemplate.html

If native WC is required, then indeed we should remove the polyfill and feature detect WC.

**Comment by miyconst** [comment]
>Do we really rely on native web components?

Potentially we could achieve proper functionality under Firefox and IE, because Polymer works under those browsers, but currently our applications, starting from Launcher, do not work under any browser except Chrome.

One of the reasons might be is that events fire order is different for native support and polyfill support.

**Comment by miyconst** [comment]
Added such message:

Firefox:
![image](https://cloud.githubusercontent.com/assets/6435556/9231830/0e4278e0-4133-11e5-931c-194ad686c483.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/6435556/9231900/57fa9aee-4133-11e5-9aca-efd59717f822.png)

IE:
![image](https://cloud.githubusercontent.com/assets/6435556/9231948/a9f4c2e8-4133-11e5-8946-f4aaafeefdc0.png)

**Comment by miyconst** [comment]
IE does not load or does not applies styles from style sheet file, inline styles works fine, but I would like to keep them in the file.

Firefox does not display the message if `layout.css.grid.enabled` set to `true`, but does not work either.

**Comment by warpech** [comment]
@tomalec any idea what to use for feature detection that would exclude Firefox even if `layout.css.grid.enabled` is `true`?

**Comment by warpech** [comment]
One way: if it supports `display: -moz-grid`, then it's Firefox :)

**Comment by warpech** [comment]
For me IE11 showed the styles, but after really long time:

![ie](https://cloud.githubusercontent.com/assets/566463/9248071/128ce648-41b9-11e5-8624-99fbd294e5e6.png)

Personally I would prefer to remove the "Dismiss" button and hide Launcher UI totally if the modal is present. @miyconst, @tomalec wdyt?

**Comment by miyconst** [comment]
Okay, I have removed the dismiss button and added block ui layer.

The `display: -moz-grid` hack works ))

**Comment by miyconst** [comment]
Released and uploaded to app store.
