### ISSUE TITLE
Sometimes the launchpad doesn't show up

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Launcher#146]
See the screenshot:

<img width="1423" alt="screenshot 2015-08-11 13 38 20" src="https://cloud.githubusercontent.com/assets/566463/9196720/5388faf6-402e-11e5-8b14-9f95027ce817.png">

**Comment by miyconst** [comment]
I have met this issue several times, but was not able to reproduce on purpose. I have pushed an attempt to fix the issue, but not sure it will actually work.

**Comment by warpech** [comment]
Thanks! Let's close it since I haven't seen it in a while
