### ISSUE TITLE
Separate launch pad

### ISSUE THREAD

**Issue by Starcounter-Jack** [Polyjuice/Launcher#73]
We've been discussing if we should have the dashboard (tiles) and launchpad (icons) as two separate things. After giving it some thought, I think it should be done.

## Motivation for a separate launchpad

There is great freedom for application to put whatever they want in the dashboard. But this freedom is not positive if the user wishes to remove or administer his/her applications. I.e. an application with crazy ideas or a buggy user interface should still be possible to remove (or launch). I.e., it would be very usable to have a launcher controlled launchpad that does not allow to much custom content. This would be were you would have a stringent way to launch, install and uninstall applications. 

Each box would contain:

1. A square sized png (1024x1024 or bigger). If none is supplied, a default one will be used. The icon will be scaled to 256x256 (512x512 on retina displays) by the launcher.

2. A label text. If none is supplied, the application identifier (SuperCRM) will be used.

![screenshot of finder 01-06-14 16 23 49](https://cloud.githubusercontent.com/assets/1219049/3141764/5f4764a6-e998-11e3-82f9-b88e2658df06.png)

The launcher will itself add the UX to start (click) and app (navigating to its workspace) or to remove it (if the user has the rights). Removing an app is done using a REST call to the server.

**Comment by warpech** [comment]
Closing, as Launchpad is already created
