### ISSUE TITLE
Uncaught Possible attempt to load Polymer twice 

### ISSUE THREAD

**Issue by andwah** [Polyjuice/Launcher#87]
I have an app that use an element ```core-ajax``` that was installed with bower.

***Web component code:***
```
<link rel="import" href="/bower_components/core-ajax/core-ajax.html">
...
```

When navigate to the launcher i get this error

***Browser console output window:***
```
Uncaught Possible attempt to load Polymer twice 
```

**Comment by miyconst** [comment]
To avoid this issue all of the bower components should be installed to `/sys/` directory, not `/bower_components/`.

Anyway, this issue seems to be outdated and no longer relevant, @andwah close it please.

**Comment by warpech** [comment]
@miyconst it would be great if you could write an explanation about that in Starcounter.io > Docs > Guides > Apps section. 

I will create a ticket for that
