### ISSUE TITLE
Apps does not have isolated access to static content

### ISSUE THREAD

**Issue by tomalec** [Polyjuice/Launcher#9]
In one app I have created [`/Apps/dummyCRM/Client/person.html`](https://github.com/Polyjuice/Launcher/blob/dc6f002b869133fc633d7f5e1f64f3a1373d4392/Apps/dummyCRM/Client/person.html), and access it (in [Master.json.cs](https://github.com/Polyjuice/Launcher/blob/dc6f002b869133fc633d7f5e1f64f3a1373d4392/Apps/dummyCRM/Server/Master.json.cs#L25)) via `/person.html`, but then in different app `/Apps/Skype`([`/Server/Master.json.cs`](https://github.com/Polyjuice/Launcher/blob/dc6f002b869133fc633d7f5e1f64f3a1373d4392/Apps/Skype/Server/Master.json.cs#L18)) I was able to access this file as well with `/person.html`. 

Is it desired behavior? It seems to break isolation of apps.

(There is a separated branch [issue-9](https://github.com/Polyjuice/Launcher/tree/issue-9) for it)

**Comment by warpech** [comment]
This is solved by putting all static files into a subdirectory with the same name as the app name (e.g. `/dummycrm/person.html`, `/skyper/person.html`).

Closing the issue and deleting the `issue-9` branch.
