### ISSUE TITLE
Change default width of elements to auto

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Launcher#98]
The layout elements which are not manually resized should have the horizontal dimension defined as `widthAuto: true` -- so that the tile width is the same as the element's intrinsic width.

Discussed with @Starcounter-Jack and @tomalec on Monday

**Comment by miyconst** [comment]
Seems like the issue related to https://github.com/Polyjuice/Polyjuice/issues/39

**Comment by tomalec** [comment]
In fact it was done long ago.
So that every element without a setup entry will get `widthAuto: true`, it does not affect creating new groups.

**Comment by miyconst** [comment]
Then close the issue, please.
